config/routes.rb
Xayot::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root to: 'welcome#index'

  resources :posts, only: [:show]
  resources :categories, only: [:index, :show]

  namespace :admin do
    root to: 'admin#index'

    resources :users, except: [:show]
    resources :cities, except: [:show]
    
    resources :actions, except: [:show] do
      get :manage, on: :collection
      post :rebuild, on: :collection

      get 'publish', on: :member
      get 'unpublish', on: :member
    end

    resources :categories do
      get :manage, on: :collection
      post :rebuild, on: :collection

      get 'publish', on: :member
      get 'unpublish', on: :member
    end

    resources :posts, except: [:show] do
      get 'publish', on: :member
      get 'unpublish', on: :member

      resources :gallery_posts, only: [:index, :create, :destroy]
    end

    resources :menus do
      collection do
        get :manage
        post :rebuild
        get :rebuild_select
      end
      
      get 'publish', on: :member
      get 'unpublish', on: :member
    end
  end
end

app/models/content/menu.rb
class Menu < ActiveRecord::Base
	scope :published, -> { where('published = ?', true) }

	include TheSortableTree::Scopes
  acts_as_nested_set

  belongs_to :post
  belongs_to :category
  belongs_to :user

  attr_accessible :parent_id, :lft, :rgt, :depth, :name, :published, :post_id, :category_id

  validates_presence_of :name
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::AdminController
	# include TheSortableTreeController::Rebuild
	include TheSortableTreeController::ReversedRebuild
  before_filter :tree, except: [:index, :manage, :create]
	before_filter :find_menu, except: [:index, :new, :create, :rebuild_select]

	def index
		# @menus = Menu.nested_set.paginate(page: params[:page], per_page: 15)
		@menus = Menu.reversed_nested_set.paginate(page: params[:page], per_page: 15)
	end

	def manage
  end

  def rebuild_select
  	@link = case params[:link_menu]
	  	when 'category' then Category.all
	  	when 'post' then Post.all
  	end
  end

	def new
		@menu = current_user.menu.build
	end

	def create
		@menu = current_user.menu.build(params[:menu])

		if @menu.save
			flash[:notice] = "Меню - #{@menu.name} успешно создано"
			redirect_to [:edit, :admin, @menu]
		else
			flash[:alert] = "При сохранении возникли ошибки"
			render 'new'
		end

	end

	def edit
	end

	def update
		params[:menu][:post_id] = nil if params[:menu][:category_id].present?
		params[:menu][:category_id] = nil if params[:menu][:post_id].present?

		if @menu.update_attributes(params[:menu])
			flash[:notice] = "Пункт меню - #{@menu.name} успешно обновлен"
			redirect_to [:edit, :admin, @menu]
		else
			render 'edit'
		end
	end

	def destroy
		@menu.destroy
		flash[:notice] = "Пункт меню - #{@menu.name} успешно удален"
		redirect_to admin_menus_path
	end

	def publish
		if @menu.update_column(:published, true)
			flash[:notice] = "Пункт меню - #{@menu.name} успешно опубликован"
		else
			flash[:alert] = "Что то пошло не так"
		end

		redirect_to admin_menus_path
	end

	def unpublish
		if @menu.update_column(:published, false)
			flash[:notice] = "Пункт меню - #{@menu.name} успешно снят с публикации"
		else
			flash[:alert] = "Что то пошло не так"
		end

		redirect_to admin_menus_path
	end

	private
		def find_menu
			@menu = Menu.find(params[:id])
		end

		def tree
      @tree = Category.nested_set.all
    end
end

app/views/admin/menus/tabs/_main_info.html.haml
.control-group
	= f.label :name, 'Название', {class: 'control-label'}
	.controls= f.text_field :name, placeholder: 'Название пункта меню'
.control-group
	= f.label 'link', 'Ссылка меню'
	.controls
		%ul.nav.nav-tabs.select_link_menu
			%li= link_to 'Категории', rebuild_select_admin_menus_path(link_menu: 'category'), remote: true
			%li.active= link_to 'Посты', rebuild_select_admin_menus_path(link_menu: 'post'), remote: true

		.select_menu
			- if @menu.category.present?
				= f.select :category_id, options_for_select(Category.all.map{|c| [c.content.name, c.id]}, @menu.category.id)
			- else
				= f.select :post_id, options_for_select(Post.all.map{|p| [p.content.name, p.id]}, @menu.post.try(:id)) if Post.count > 0
.control-group
	= f.label :published, 'Публикация', {class: 'control-label'}
	.controls= f.check_box :published