config/routes.rb
Xayot::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root to: 'welcome#index'

  resources :posts, only: [:show]
  resources :categories, only: [:index, :show]

  namespace :admin do
    root to: 'admin#index'

    resources :users, except: [:show]
    resources :cities, except: [:show]
    
    resources :actions, except: [:show] do
      get :manage, on: :collection
      post :rebuild, on: :collection

      get 'publish', on: :member
      get 'unpublish', on: :member
    end

    resources :categories do
      get :manage, on: :collection
      post :rebuild, on: :collection

      get 'publish', on: :member
      get 'unpublish', on: :member
    end

    resources :posts, except: [:show] do
      get 'publish', on: :member
      get 'unpublish', on: :member

      resources :gallery_posts, only: [:index, :create, :destroy]
    end

    resources :menus do
      collection do
        get :manage
        post :rebuild
        get :rebuild_select
      end
      
      get 'publish', on: :member
      get 'unpublish', on: :member
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  scope :published, -> { joins(:content).merge(Content.published) }
  
  include TheSortableTree::Scopes
  acts_as_nested_set

  has_one :content, as: :node, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_one :menu

  accepts_nested_attributes_for :content
  attr_accessible :content_attributes, :parent_id, :lft, :rgt, :depth
end

app/models/content/category.rb
class Category < ActiveRecord::Base
  scope :published, -> { joins(:content).merge(Content.published) }
  
  include TheSortableTree::Scopes
  acts_as_nested_set

  has_one :content, as: :node, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :actions, dependent: :destroy
  has_one :menu, dependent: :destroy

  accepts_nested_attributes_for :content
  attr_accessible :content_attributes, :parent_id
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  # include TheSortableTreeController::Rebuild
  include TheSortableTreeController::ReversedRebuild
  before_filter :tree, except: [:index, :manage, :create]
  before_filter :find_cat, only: [:update, :edit, :destroy, :publish, :unpublish]
  before_filter :seo_category_params, only: [:update, :create]

  def index
    # @categories = Category.nested_set.includes(:content).paginate(page: params[:page], per_page: 15)
    @categories = Category.reversed_nested_set.includes(:content).paginate(page: params[:page], per_page: 15)
  end

  def manage
  end

  def new
    @category = Category.new
    @content = @category.build_content
  end

  def create
    @category = Category.new(params[:category])
      
    if @category.save
      current_user.contents << @category.content
      flash[:notice] = "Категория #{@category.content.name} успешно создана"
      redirect_to [:edit, :admin, @category]
    else
      render 'new'
    end
  end

  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Информация о категории #{@category.content.name} успешно обновлена"
    else
      flash[:alert] = 'Ошибка обновления'
    end

    redirect_to [:edit, :admin, @category]
  end

  def edit
  end

  def destroy
    @category.destroy
    flash[:notice] = "Категория - #{@category.content.name} успешно удалена"
    redirect_to admin_categories_path
  end

  def publish
    @category.content.published = true

    if @category.save
      flash[:notice] = "Категория ##{@category.id} успешно опубликована"
    else
      flash[:alert] = 'Опс, что то пошло не так' 
    end
    
    redirect_to [:edit, :admin, @category]
  end

  def unpublish
    @category.content.published = false
    
    if @category.save
      flash[:notice] = "Категория ##{@category.id} успешно снята с публикации"
    else
      flash[:alert] = 'Опс, что то пошло не так'
    end
    
    redirect_to [:edit, :admin, @category] 
  end

  private
    def tree
      @tree = Category.nested_set.all
    end

    def find_cat
      @category = Category.find(params[:id])
    end

    def seo_category_params
      params[:category][:content_attributes][:seo] = params[:seo].to_json
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	add_breadcrumb "Главная", :root_path

	def index
	end

	def show
		@category = Category.find(params[:id])
		@posts = @category.posts.paginate(page: params[:page], per_page: 15)

		add_breadcrumb @category.content.name, @category
	end
end

app/views/admin/categories/_errors.html.haml
- if @category.errors.any?
  #errorExplanation.alert.alert-error
    %h4
      = pluralize(@category.errors.count, 'error') 
      prohibited this category from being saved:
    %ul
      - @category.errors.full_messages.each do |e|
        %li= e

app/views/admin/categories/_form.html.haml
= form_for [:admin, @category], html: {class: 'form-horizontal'} do |f|
  = render 'errors'
  .btn-toolbar
    .btn-group
      = f.submit 'Сохранить', :class => 'btn btn-primary'
      = f.button 'Отмена', :class => 'btn', :type => 'reset'
    .btn-group.pull-right
      = button_item({link_new: new_admin_category_path, text_new: 'Новая категория', link_all: admin_categories_path, text_all: 'Все категории'})
  .tabbable
    %ul.nav.nav-tabs.clickTabs{data: {tabs: 'tabs'}}
      = render 'admin/categories/tabs/menu'
  = f.fields_for :content do |c|
    .tab-content
      .tab-pane.active#main_info
        = render 'admin/categories/tabs/main_info', f: f, c: c
      .tab-pane#seo
        = render 'admin/categories/tabs/seo'
      .tab-pane#bg
        = render 'admin/categories/tabs/bg', c: c

app/views/admin/categories/edit.html.haml
%h3= "Редактирование категории #{@category.content.name}" 
= render 'form' 

app/views/admin/categories/index.html.haml
.btn-toolbar
  .btn-group.pull-right
    = button_new_item({link_new: new_admin_category_path, text_new: 'Новая категория'})
%h3 Все категории
= will_paginate(@categories, next_label: '>', previous_label: '<', class: 'pagination pagination-mini')
%ol.sortable_tree{data: {rebuild_url: rebuild_admin_categories_url}}
  = sortable_tree @categories, {namespace: :admin}
= will_paginate(@categories, next_label: '>', previous_label: '<', class: 'pagination pagination-mini')

app/views/admin/categories/new.html.haml
%h3 Создание новой категории
= render 'form'