config/routes.rb
Xayot::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root to: 'welcome#index'

  resources :posts, only: [:show]
  resources :categories, only: [:index, :show]

  namespace :admin do
    root to: 'admin#index'

    resources :users, except: [:show]
    resources :cities, except: [:show]
    
    resources :actions, except: [:show] do
      get :manage, on: :collection
      post :rebuild, on: :collection

      get 'publish', on: :member
      get 'unpublish', on: :member
    end

    resources :categories do
      get :manage, on: :collection
      post :rebuild, on: :collection

      get 'publish', on: :member
      get 'unpublish', on: :member
    end

    resources :posts, except: [:show] do
      get 'publish', on: :member
      get 'unpublish', on: :member

      resources :gallery_posts, only: [:index, :create, :destroy]
    end

    resources :menus do
      collection do
        get :manage
        post :rebuild
        get :rebuild_select
      end
      
      get 'publish', on: :member
      get 'unpublish', on: :member
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body

  has_many :contents, dependent: :destroy
end

app/models/user/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, :all if user.role.admin?
    can :read, [Post, Category] if user.role.user?
  end
end

app/models/user/user.rb
class User < ActiveRecord::Base
  scope :order_desc, -> { order('id DESC') }
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, 
  								:first_name, :last_name, :description, :contacts

  has_many :contents, dependent: :destroy
  has_many :menu, dependent: :destroy
  belongs_to :city
  has_many :actions, dependent: :destroy

  def role
    self[:role].inquiry
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_filter :find_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order_desc.paginate(page: params[:page], per_page: 15)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new params[:user]

    if @user.save
      flash[:notice] = "Пользователь '#{@user.first_name} #{@user.last_name}' успешно сохранен"
      redirect_to [:edit, :admin, @user]
    else
      flash[:alert] = "При сохранении возникли ошибки"
      render 'new'
    end
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = "Пользователь #{@user.email} успешно обновлен"
      redirect_to [:edit, :admin, @user]
    else
      flash[:alert] = "При обновлении возникли ошибки"
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "Пользователь '#{@user.first_name} #{@user.last_name}' успешно удален"
    redirect_to [:admin, :users]
  end

  private
    def find_user
      @user = User.find(params[:id])
    end
end

app/views/admin/users/_errors.html.haml
- if @user.errors.any?
  #errorExplanation.alert.alert-error
    %h4
      = pluralize(@user.errors.count, 'error') 
      prohibited this user from being saved:
    %ul
      - @user.errors.full_messages.each do |e|
        %li= e

app/views/admin/users/_form.html.haml
= form_for [:admin, @user], html: {class: 'form-horizontal'} do |f|
  = render 'errors'
  .btn-toolbar
    .btn-group
      = f.submit 'Сохранить', class: 'btn btn-primary'
      = f.button 'Отмена', class: 'btn', type: 'reset'
    .btn-group.pull-right
      = button_item({link_new: [:new, :admin, :user], text_new: 'Новый пользователь', link_all: [:admin, :users], text_all: 'Все пользователи'})
  .tabbable
    %ul.nav.nav-tabs.clickTabs{data: {tabs: 'tabs'}}
      = render 'admin/users/tabs/menu'
  .tab-content
    .tab-pane.active#main_info= render 'admin/users/tabs/main_info', f: f
    .tab-pane#additional_info= render 'admin/users/tabs/additional_info' unless @user.new_record?
    .tab-pane#contacts= render 'admin/users/tabs/contacts', f: f

app/views/admin/users/_user.html.haml
%tr
	%td= user.id
	%td= (can?(:edit, current_user))? link_to("#{user.first_name} #{user.last_name}", [:edit, :admin, user]) : "#{user.first_name} #{user.last_name}"
	%td= user.email
	%td= user.role
	%td= delete_link({delete_link: admin_user_path(user), message: "Уверены что хотите удалить пользователя '#{user.first_name} #{user.last_name}'"}) if can? :delete, current_user

app/views/admin/users/edit.html.haml
%h3= @user.first_name
= render 'form'

app/views/admin/users/index.html.haml
.btn-toolbar
  .btn-group.pull-right= button_new_item({link_new: new_admin_user_path, text_new: 'Новый пользователь'}) if can? :create, current_user
%h3 Пользователи
= will_paginate(@users, next_label: '>', previous_label: '<', class: 'pagination pagination-mini')
%table.table.table-bordered.table-striped
  %tr
    %th #
    %th Ф.И.О.
    %th Email
    %th Роль
    %th
  = render @users
= will_paginate(@users, next_label: '>', previous_label: '<', class: 'pagination pagination-mini')

app/views/admin/users/new.html.haml
%h3 Новый пользователь
= render 'form'